kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nlp
  template:
    metadata:
      labels:
        app: deploy-nlp
    spec:
      containers:
      - name: deploy-nlp
        image: frogdance/deploy_nlp
        ports:
        - containerPort: 8000