apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: deploy-nlp
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 31000
  selector:
    app: deploy-nlp